name: Merge

on:
  push:
  schedule:
    - cron: "30 8 * * *"

env:
  CARGO_TERM_COLOR: always
  slack-channel: 'alerts'

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:

  lint_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Lint Website
        run: just lint

      - name: Notify Slack of Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  publish_docker:
    needs: [lint_website]
    if: >-
      (github.ref == 'refs/heads/refresh' && github.repository_owner == 'hyperledger')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Website
        run: just docker-build

      - name: Publish site to dockerhub
        run: docker push hyperledger/sawtooth-website:refresh

      - name: Notify Slack of Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
